# Verwende ein offizielles Python-Image als Basis
FROM python:3.11-slim

# Setze das Arbeitsverzeichnis im Container
WORKDIR /mqtt_listener

# Kopiere die requirements-Datei und installiere Abhängigkeiten
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Kopiere den Rest des Anwendungscodes
COPY . .

EXPOSE 6789

# Setze den Standardbefehl zum Starten der Anwendung (z.B. Flask)
CMD ["python", "-u", "mqtt_listener.py"]